package org.hongtao.model;

public enum InterfaceName {
    USERISREGISTERED,
    GETLATESTVERSION,
    APPUSERLOGIN,
    PUTUSERPASSWORD,
    REGISTERVERIFYCODE,
    GETAPPINDEXPRODUCTINFO,
    GETAPPINDEXRESULT,
    UPLOADFILE,
    UPDATEUSERINFOFACEURL,
    INSERTUSERAADHAARCARD,
    QUERYCERTIFICATIONSTATUS,
    INSERTUSERPANCARD,
    INSERTUSERFILES,
    GETUPDATEUSERINFO,
    GETUPDATEUSERSTUDENT,
    GETUPDATEUSERWORK,
    GETUSERBANKCARD,
    GETUSERCONTACT,
    INSERTUSERCONTACT,
    INSERTUSERBANKCARD,
    APPLYSUBMIT,
    UPDATEUSERINFO,
    UPDATEUSERWORK
}
